### ISSUE TITLE
Automatic linux build through travis-ci

### ISSUE THREAD

**Issue by febs** [hobbyquaker/arcticfox-config#23]
Hi,
the home page of the project states that there should be a .deb package for Ubuntu/Debian along with the OsX package and the source code, but I couldn't find it.

Thank you!

**Comment by hobbyquaker** [comment]
sry, still have to fix the automatic build, shame on me ;) will do asap. until then you can build on your own, instructions are here: https://nfeteam.org/forum/threads/arcticfox-configuration-for-macos-and-linux.268/#post-1736

**Comment by febs** [comment]
Thank you!

**Comment by febs** [comment]
Ouch! It fails.

Here's some of the output.

electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

```
> > To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your 
> > `package.json`
> > Rebuilding native production dependencies for linux:x64
> > Packaging for linux x64 using electron 1.7.5 to dist/linux-unpacked
> > Downloading tmp-17126-0-electron-v1.7.5-linux-x64.zip
> > [>                                            ] 0.0% (0 B/s)
> > **Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT**
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder-util/src/util.ts:78:16
> >     at exithandler (child_process.js:277:5)
> >     at ChildProcess.errorhandler (child_process.js:289:5)
> >     at emitOne (events.js:115:13)
> >     at ChildProcess.emit (events.js:210:7)
> >     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> >     at onErrorNT (internal/child_process.js:374:16)
> >     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> >     at process._tickCallback (internal/process/next_tick.js:180:9)
> > From previous event:
> >     at exec (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder-util/src/util.ts:56:3)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:180:28
> >     at Generator.next (<anonymous>)
> >     at runCallback (timers.js:781:20)
> >     at tryOnImmediate (timers.js:743:5)
> >     at processImmediate [as _immediateCallback] (timers.js:714:5)
> > From previous event:
> >     at LinuxTargetHelper.createFromIcns (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/targets/LinuxTarget
> > Helper.js:221:11)
> >     at new LinuxTargetHelper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:1
> > 7:23)
> >     at getHelper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:33:18)
> >     at outDir (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:62:122)
> >     at mapper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/targetFactory.ts:50:16)
> >     at LinuxPackager.createTargets (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:62:7)
> >     at createTargets (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/targetFactory.ts:57:12)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/packager.ts:233:28
> > From previous event:
> >     at Packager.doBuild (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/packager.js:340:11)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/packager.ts:184:52
> >     at Generator.next (<anonymous>)
> > From previous event:
> >     at Packager.build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/packager.js:259:11)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/builder.ts:266:40
> >     at Generator.next (<anonymous>)
> >     at build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/builder.js:69:21)
> >     at loadEnv.then (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
> > From previous event:
> >     at build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/builder.js:69:21)
> >     at loadEnv.then (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:155:79)
> >     at runCallback (timers.js:781:20)
> >     at tryOnImmediate (timers.js:743:5)
> >     at processImmediate [as _immediateCallback] (timers.js:714:5)
> > From previous event:
> >     at Object.args [as handler] (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:155:68)
> >     at Object.self.runCommand (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/lib/command.js:233:22)
> >     at Object.Yargs.self._parseArgs (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/yargs.js:1018:24)
> >     at Object.get [as argv] (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/yargs.js:927:19)
> >     at Object.<anonymous> (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:151:465)
> >     at Module._compile (module.js:573:30)
> >     at Object.Module._extensions..js (module.js:584:10)
> >     at Module.load (module.js:507:32)
> >     at tryModuleLoad (module.js:470:12)
> >     at Function.Module._load (module.js:462:3)
> >     at Function.Module.runMain (module.js:609:10)
> >     at startup (bootstrap_node.js:158:16)
> > Downloading tmp-17126-1-SHASUMS256.txt-1.7.5
> > [============================================>] 100.0% of 2.93 kB (2.93 kB/s)
> > Building tar.gz
> > Building deb
> > Error: Exit code: ENOENT. spawn icns2png ENOENT
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder-util/src/util.ts:78:16
> >     at exithandler (child_process.js:277:5)
> >     at ChildProcess.errorhandler (child_process.js:289:5)
> >     at emitOne (events.js:115:13)
> >     at ChildProcess.emit (events.js:210:7)
> >     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> >     at onErrorNT (internal/child_process.js:374:16)
> >     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> >     at process._tickCallback (internal/process/next_tick.js:180:9)
> > From previous event:
> >     at exec (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder-util/src/util.ts:56:3)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:180:28
> >     at Generator.next (<anonymous>)
> >     at runCallback (timers.js:781:20)
> >     at tryOnImmediate (timers.js:743:5)
> >     at processImmediate [as _immediateCallback] (timers.js:714:5)
> > From previous event:
> >     at LinuxTargetHelper.createFromIcns (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/targets/LinuxTarget
> > Helper.js:221:11)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:54:25
> > From previous event:
> >     at LinuxTargetHelper.computeDesktopIcons (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/targets/LinuxT
> > argetHelper.js:84:11)
> >     at new LinuxTargetHelper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:1
> > 7:23)
> >     at getHelper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:33:18)
> >     at outDir (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:62:122)
> >     at mapper (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/targetFactory.ts:50:16)
> >     at LinuxPackager.createTargets (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/linuxPackager.ts:62:7)
> >     at createTargets (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/targets/targetFactory.ts:57:12)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/packager.ts:233:28
> > From previous event:
> >     at Packager.doBuild (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/packager.js:340:11)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/packager.ts:184:52
> >     at Generator.next (<anonymous>)
> > From previous event:
> >     at Packager.build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/packager.js:259:11)
> >     at /home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/builder.ts:266:40
> >     at Generator.next (<anonymous>)
> >     at build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/builder.js:69:21)
> >     at loadEnv.then (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
> > From previous event:
> >     at build (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/builder.js:69:21)
> >     at loadEnv.then (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:155:79)
> >     at runCallback (timers.js:781:20)
> >     at tryOnImmediate (timers.js:743:5)
> >     at processImmediate [as _immediateCallback] (timers.js:714:5)
> > From previous event:
> >     at Object.args [as handler] (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:155:68)
> >     at Object.self.runCommand (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/lib/command.js:233:22)
> >     at Object.Yargs.self._parseArgs (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/yargs.js:1018:24)
> >     at Object.get [as argv] (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/yargs/yargs.js:927:19)
> >     at Object.<anonymous> (/home/fabio/devel/others/Vaping/arcticfox-config-1.10.0/node_modules/electron-builder/out/cli/cli.js:151:465)
> >     at Module._compile (module.js:573:30)
> >     at Object.Module._extensions..js (module.js:584:10)
> >     at Module.load (module.js:507:32)
> >     at tryModuleLoad (module.js:470:12)
> >     at Function.Module._load (module.js:462:3)
> >     at Function.Module.runMain (module.js:609:10)
> >     at startup (bootstrap_node.js:158:16)
> >     at bootstrap_node.js:598:3
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 255
> > npm ERR! arcticfox-config@1.10.0 dist: `build`
> > npm ERR! Exit status 255
> > 
> 
```

Thank you :-)

**Comment by hobbyquaker** [comment]
oh, icns2png missing, try `apt-get install icnsutils` (if you're on debian based distro)

**Comment by febs** [comment]
I also had to install `graphicsmagick`, then the build ran and I got the .deb package, thanks!

**Comment by hobbyquaker** [comment]
let us keep this issue open until the automatic linux builds are running ;)
