### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Dil3mm4** [hobbyquaker/arcticfox-config#29]
Followed the instruction over AF Forum that's the result:
```
[root@lazydev arcticfox-config]# node_modules/.bin/electron-rebuild 
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/ACFOX/arcticfox-config/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/ACFOX/arcticfox-config/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/ACFOX/arcticfox-config/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.electron-gyp/.node-gyp/iojs-1.7.6/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.electron-gyp/.node-gyp/iojs-1.7.6',
gyp info spawn args   '-Dnode_gyp_dir=/root/ACFOX/arcticfox-config/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.electron-gyp/.node-gyp/iojs-1.7.6/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/ACFOX/arcticfox-config/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: ingresso nella directory "/root/ACFOX/arcticfox-config/node_modules/node-hid/build"
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:10: fatal error: libusb.h: File o directory non esistente
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [hidapi.target.mk:96: Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: uscita dalla directory "/root/ACFOX/arcticfox-config/node_modules/node-hid/build"
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/ACFOX/arcticfox-config/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.12.9-300.fc26.x86_64
gyp ERR! command "/usr/bin/node" "/root/ACFOX/arcticfox-config/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /root/ACFOX/arcticfox-config/node_modules/node-hid
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/ACFOX/arcticfox-config/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/ACFOX/arcticfox-config/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/ACFOX/arcticfox-config/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.electron-gyp/.node-gyp/iojs-1.7.6/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.electron-gyp/.node-gyp/iojs-1.7.6',
gyp info spawn args   '-Dnode_gyp_dir=/root/ACFOX/arcticfox-config/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.electron-gyp/.node-gyp/iojs-1.7.6/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/ACFOX/arcticfox-config/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: ingresso nella directory "/root/ACFOX/arcticfox-config/node_modules/node-hid/build"
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:10: fatal error: libusb.h: File o directory non esistente
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [hidapi.target.mk:96: Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: uscita dalla directory "/root/ACFOX/arcticfox-config/node_modules/node-hid/build"
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/ACFOX/arcticfox-config/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.12.9-300.fc26.x86_64
gyp ERR! command "/usr/bin/node" "/root/ACFOX/arcticfox-config/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /root/ACFOX/arcticfox-config/node_modules/node-hid
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/root/ACFOX/arcticfox-config/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/root/ACFOX/arcticfox-config/node_modules/spawn-rx/lib/src/index.js:241:65)
    at SafeSubscriber.__tryOrSetError (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:247:16)
    at SafeSubscriber.next (/root/ACFOX/arcticfox-config/node_modules/rxjs/Subscriber.js:187:27)
```

There seem to be a missing lib.
P.S. Another good thing would be the inclusion of .rpm packages building as well.

**Comment by hobbyquaker** [comment]
I think you need `libusb-1.0-0-dev` (apt) respectively `libusb-devel` (rpm).

**Comment by Dil3mm4** [comment]
nvm i'll fix it

**Comment by Dil3mm4** [comment]
Correctly build, rpm too with alien. 
If you want I can submit the compiled files everytime you update the source.

**Comment by hobbyquaker** [comment]
Thanks for the offer, but I think it won't be necessary. Got the automated linux build with travis running, you will find a new release soon.
