### ISSUE TITLE
failed to run: i18n/cs.json not found (czech localization)

### ISSUE THREAD

**Issue by magor** [hobbyquaker/arcticfox-config#31]
Hi guys, I tried to run this app from latest 1.11.5 binary release, but it fails:

```
$ ./arcticfox-config 
{ Error: ENOENT, i18n/cs.json not found in /home/x/git/aur-arcticfox-config/test/src/arcticfox-config-1.11.5/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:513:9)
    at App.app.on (/home/x/git/aur-arcticfox-config/test/src/arcticfox-config-1.11.5/resources/app.asar/main.js:424:30)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7) code: 'ENOENT', errno: -2 }
```

It runs when started like this: `LANG=en ./arcticfox-config`. I guess there could be problem with naming of json file: `arcticfox-config/i18n/cz.json` (location is CZ, but language cs - thus locale is `cs_CZ`).

I can't test it right now, because manual build seems to be broken.

**Comment by hobbyquaker** [comment]
Thx for reporting, build with fixed fallback to english and cs.json is on the way
