### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by sdevmaster** [hobbyquaker/arcticfox-config#42]
It connects and shows me the settings from my arcticfox, but if i change something and press upload, it saves something completely different from what i have entered, e.g. it saves TC settings instead of VW or something like that, each time i hit save it feels like a dice. So at present, the whole program is useless.

**Comment by hobbyquaker** [comment]
tried to reproduce that with Arcticfox 171126 and Arcticfox-Config 1.11.8 - but couldn't. Would be nice if you help me by exporting your config to a file, then upload to the device, download from the device again and export to a file once more and hand me over both files.

**Comment by sdevmaster** [comment]
Versions are correct, arcticfox is 171126 and Arcticfox-Config is 1.11.8. OS is NixOS, which is a very special linux but nevertheless a linux, so i think it should work. Tried to help you with this, but when i try to export the config, this message appears:

```
Uncaught Exception:
ReferenceError: lineContent is not defined
    at Object.Model.Interface.ClassicSkinVWLines.Line1 (/home/steffen/projects/arcticfox_config/arcticfox-config-1.11.8/resources/app.asar/afcfile.js:584:63)
    at Object.keys.forEach.Key (/home/steffen/projects/arcticfox_config/arcticfox-config-1.11.8/resources/app.asar/afcfile.js:1084:33)
    at Array.forEach (native)
    at AfcFile.conf2xml (/home/steffen/projects/arcticfox_config/arcticfox-config-1.11.8/resources/app.asar/afcfile.js:1081:26)
    at electron.dialog.showSaveDialog.filename (/home/steffen/projects/arcticfox_config/arcticfox-config-1.11.8/resources/app.asar/main.js:167:58)
    at Function.wrappedCallback (/home/steffen/projects/arcticfox_config/arcticfox-config-1.11.8/resources/electron.asar/browser/api/dialog.js:189:14)
```
Hope this helps to point you in the right direction.
